import NavBar from "@/components/NavBar";
import PageFooter from "@/components/PageFooter";
import AppBreadcrumb from "@/components/layout/AppBreadcrumb";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { FileText, AlertTriangle, Scale, Shield, Users, Ban, RefreshCw } from "lucide-react";

export default function TermsOfService() {
  const lastUpdated = "January 16, 2026";
  
  return (
    <div className="min-h-screen bg-background">
      <NavBar />
      
      <main className="container py-8 max-w-4xl">
        <AppBreadcrumb className="mb-4" />
        
        <div className="flex items-center gap-3 mb-6">
          <div className="p-3 bg-primary/20 rounded-xl">
            <FileText className="h-8 w-8 text-primary" />
          </div>
          <div>
            <h1 className="text-3xl font-bold">Terms of Service</h1>
            <p className="text-muted-foreground">Last updated: {lastUpdated}</p>
          </div>
        </div>

        {/* Important Disclaimer Banner */}
        <Card className="mb-8 border-amber-500/50 bg-gradient-to-r from-amber-500/10 to-transparent">
          <CardContent className="p-6">
            <div className="flex gap-4">
              <AlertTriangle className="h-6 w-6 text-amber-500 flex-shrink-0 mt-1" />
              <div>
                <h3 className="font-bold text-lg mb-2 text-amber-500">Important Notice</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  EdgeIQ is a <strong>sports analytics and prediction platform</strong> designed for 
                  educational and entertainment purposes only. We are <strong>NOT a sportsbook, gambling operator, 
                  or licensed betting platform</strong>. We do not accept wagers, process bets, or handle any 
                  gambling-related transactions. All predictions are generated by statistical algorithms and 
                  <strong> should not be relied upon as financial or gambling advice</strong>.
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        <div className="space-y-6">
          {/* Agreement Section */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Scale className="h-5 w-5 text-primary" />
                1. Agreement to Terms
              </CardTitle>
            </CardHeader>
            <CardContent className="prose prose-sm dark:prose-invert max-w-none">
              <p>
                By accessing or using EdgeIQ ("the Service"), you agree to be bound by these 
                Terms of Service. If you do not agree to these terms, you must not access or use the Service.
              </p>
              <p>
                You must be at least 18 years of age (or the legal age of majority in your jurisdiction) to 
                use this Service. By using the Service, you represent and warrant that you meet this age requirement.
              </p>
            </CardContent>
          </Card>

          {/* Nature of Service */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Shield className="h-5 w-5 text-primary" />
                2. Nature of Service
              </CardTitle>
            </CardHeader>
            <CardContent className="prose prose-sm dark:prose-invert max-w-none">
              <h4>2.1 What We Provide</h4>
              <ul>
                <li>Statistical analysis and data visualization of sports events</li>
                <li>AI-generated predictions based on historical data and algorithms</li>
                <li>Educational content about sports analytics and betting concepts</li>
                <li>Bankroll management tools and calculators</li>
                <li>Performance tracking and backtesting capabilities</li>
              </ul>
              
              <h4>2.2 What We Do NOT Provide</h4>
              <ul>
                <li>Gambling or betting services of any kind</li>
                <li>Financial advice, investment advice, or gambling advice</li>
                <li>Guaranteed outcomes or "sure bets"</li>
                <li>Licensed tipster or handicapping services</li>
                <li>Any form of wagering or betting platform</li>
              </ul>
            </CardContent>
          </Card>

          {/* Disclaimer of Warranties */}
          <Card className="border-destructive/30">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <AlertTriangle className="h-5 w-5 text-destructive" />
                3. No Guarantee of Accuracy
              </CardTitle>
            </CardHeader>
            <CardContent className="prose prose-sm dark:prose-invert max-w-none">
              <p className="text-destructive font-semibold">
                ALL PREDICTIONS AND ANALYTICS ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND.
              </p>
              <p>
                We make no representations or warranties, express or implied, regarding:
              </p>
              <ul>
                <li>The accuracy, reliability, or completeness of any predictions</li>
                <li>The suitability of our analysis for any particular purpose</li>
                <li>The profitability or success of any betting strategy</li>
                <li>The timeliness or availability of data</li>
              </ul>
              <p>
                Past performance of our algorithms does not guarantee future results. Sports outcomes are 
                inherently unpredictable, and no analytical model can accurately predict every outcome.
              </p>
            </CardContent>
          </Card>

          {/* User Responsibilities */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Users className="h-5 w-5 text-primary" />
                4. User Responsibilities
              </CardTitle>
            </CardHeader>
            <CardContent className="prose prose-sm dark:prose-invert max-w-none">
              <p>By using this Service, you acknowledge and agree that:</p>
              <ul>
                <li>You are solely responsible for any decisions you make based on our analytics</li>
                <li>You will comply with all applicable laws in your jurisdiction regarding sports betting</li>
                <li>You will not use the Service if online gambling is prohibited in your location</li>
                <li>You will gamble responsibly and within your financial means</li>
                <li>You understand that gambling can be addictive and will seek help if needed</li>
                <li>You will not hold us liable for any losses incurred from betting decisions</li>
              </ul>
            </CardContent>
          </Card>

          {/* Limitation of Liability */}
          <Card className="border-destructive/30">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Ban className="h-5 w-5 text-destructive" />
                5. Limitation of Liability
              </CardTitle>
            </CardHeader>
            <CardContent className="prose prose-sm dark:prose-invert max-w-none">
              <p className="uppercase font-semibold">
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, EDGEIQ AND ITS AFFILIATES SHALL NOT 
                BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES,
                INCLUDING BUT NOT LIMITED TO:
              </p>
              <ul>
                <li>Loss of profits or anticipated profits</li>
                <li>Loss of data or business opportunities</li>
                <li>Financial losses from gambling or betting activities</li>
                <li>Any damages arising from reliance on our predictions or analytics</li>
              </ul>
              <p>
                This limitation applies regardless of whether the damages arise from breach of contract, 
                tort (including negligence), or any other legal theory.
              </p>
            </CardContent>
          </Card>

          {/* Changes to Terms */}
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <RefreshCw className="h-5 w-5 text-primary" />
                6. Changes to Terms
              </CardTitle>
            </CardHeader>
            <CardContent className="prose prose-sm dark:prose-invert max-w-none">
              <p>
                We reserve the right to modify these Terms of Service at any time. Changes will be effective 
                immediately upon posting to the Service. Your continued use of the Service after any changes 
                constitutes acceptance of the new terms.
              </p>
              <p>
                We encourage you to review these Terms periodically for any updates or changes.
              </p>
            </CardContent>
          </Card>

          {/* Contact */}
          <Card>
            <CardHeader>
              <CardTitle>7. Contact Information</CardTitle>
            </CardHeader>
            <CardContent className="prose prose-sm dark:prose-invert max-w-none">
              <p>
                If you have any questions about these Terms of Service, please contact us at:
              </p>
              <p className="font-medium">legal@edgeiq.app</p>
            </CardContent>
          </Card>
        </div>
      </main>
      
      <PageFooter />
    </div>
  );
}
