import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { AlertTriangle, X, Info, ExternalLink } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Link } from "react-router-dom";
import { cn } from "@/lib/utils";

interface PredictionDisclaimerProps {
  variant?: "banner" | "compact" | "inline";
  dismissible?: boolean;
  className?: string;
}

const DISMISSED_KEY = "betsmart_disclaimer_dismissed";
const DISMISS_DURATION_HOURS = 24;

export function PredictionDisclaimer({ 
  variant = "banner", 
  dismissible = true,
  className 
}: PredictionDisclaimerProps) {
  const [isDismissed, setIsDismissed] = useState(() => {
    if (!dismissible) return false;
    const dismissedAt = localStorage.getItem(DISMISSED_KEY);
    if (dismissedAt) {
      const timestamp = parseInt(dismissedAt, 10);
      const hoursSinceDismissed = (Date.now() - timestamp) / (1000 * 60 * 60);
      return hoursSinceDismissed < DISMISS_DURATION_HOURS;
    }
    return false;
  });

  const handleDismiss = () => {
    localStorage.setItem(DISMISSED_KEY, Date.now().toString());
    setIsDismissed(true);
  };

  if (isDismissed) return null;

  if (variant === "compact") {
    return (
      <motion.div
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
        className={cn(
          "flex items-center gap-2 px-3 py-2 rounded-lg bg-amber-500/10 border border-amber-500/20 text-xs",
          className
        )}
      >
        <Info className="h-3.5 w-3.5 text-amber-500 flex-shrink-0" />
        <span className="text-muted-foreground">
          Predictions are for entertainment only. 
          <Link to="/terms" className="text-primary hover:underline ml-1">
            View disclaimer
          </Link>
        </span>
        {dismissible && (
          <Button 
            variant="ghost" 
            size="icon" 
            className="h-5 w-5 ml-auto" 
            onClick={handleDismiss}
          >
            <X className="h-3 w-3" />
          </Button>
        )}
      </motion.div>
    );
  }

  if (variant === "inline") {
    return (
      <p className={cn("text-xs text-muted-foreground italic", className)}>
        ⚠️ For entertainment purposes only. No accuracy guaranteed.{" "}
        <Link to="/responsible-gambling" className="text-primary hover:underline">
          Gamble responsibly
        </Link>
      </p>
    );
  }

  // Default: full banner
  return (
    <AnimatePresence>
      <motion.div
        initial={{ opacity: 0, height: 0 }}
        animate={{ opacity: 1, height: "auto" }}
        exit={{ opacity: 0, height: 0 }}
        className={cn(
          "relative overflow-hidden rounded-lg border border-amber-500/30 bg-gradient-to-r from-amber-500/10 via-amber-500/5 to-transparent",
          className
        )}
      >
        <div className="p-4 pr-12">
          <div className="flex gap-3">
            <div className="p-2 bg-amber-500/20 rounded-lg flex-shrink-0">
              <AlertTriangle className="h-5 w-5 text-amber-500" />
            </div>
            <div className="flex-1">
              <h4 className="font-semibold text-amber-500 mb-1 text-sm">
                Disclaimer: For Entertainment Only
              </h4>
              <p className="text-xs text-muted-foreground leading-relaxed mb-2">
                All predictions and analytics on this platform are generated by statistical algorithms 
                for <strong>educational and entertainment purposes only</strong>. They do not constitute 
                gambling advice, and no accuracy or profit is guaranteed. Past performance does not 
                predict future results.
              </p>
              <div className="flex flex-wrap gap-3 text-xs">
                <Link 
                  to="/terms" 
                  className="inline-flex items-center gap-1 text-primary hover:underline"
                >
                  Terms of Service
                  <ExternalLink className="h-3 w-3" />
                </Link>
                <Link 
                  to="/responsible-gambling" 
                  className="inline-flex items-center gap-1 text-primary hover:underline"
                >
                  Responsible Gambling
                  <ExternalLink className="h-3 w-3" />
                </Link>
                <a 
                  href="tel:1-800-522-4700" 
                  className="inline-flex items-center gap-1 text-green-500 hover:underline"
                >
                  Problem Gambling Helpline: 1-800-522-4700
                </a>
              </div>
            </div>
          </div>
        </div>
        
        {dismissible && (
          <Button
            variant="ghost"
            size="icon"
            className="absolute top-2 right-2 h-8 w-8 text-muted-foreground hover:text-foreground"
            onClick={handleDismiss}
          >
            <X className="h-4 w-4" />
          </Button>
        )}
      </motion.div>
    </AnimatePresence>
  );
}
