import { Dictionary } from "@/types/utilities";
import { Sportsbook } from "@/types";

export const SPORTSBOOK_LOGOS: Dictionary<string> = {
  draftkings: "https://sportsbook.draftkings.com/assets/US_NewDesign/content/navigation/DK_Sportsbook_logo.svg",
  betmgm: "https://content.betmgm.com/content/dam/betmgm/core/images/logos/betmgm-logo.svg",
  fanduel: "https://www.pngitem.com/pimgs/m/595-5957184_fanduel-logo-png-transparent-png.png",
  "william-hill": "https://www.caesars.com/content/dam/william-hill/logos/wh-logo.svg",
  "points-bet": "https://pbs.twimg.com/profile_images/1435349927915788291/ENlu0wOU_400x400.png",
  "unibet": "https://logos-world.net/wp-content/uploads/2021/02/Unibet-Logo.png",
  "888sport": "https://upload.wikimedia.org/wikipedia/fr/thumb/f/f4/888sport.svg/1200px-888sport.svg.png",
  "betway": "https://www.digitaltveurope.com/files/2021/06/Betway-logo.jpg",
  "bwin": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Bwin.svg/2560px-Bwin.svg.png",
  "coral": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Coral_logo.svg/2560px-Coral_logo.svg.png",
  "ladbrokes": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Ladbrokes_Logo.svg/2560px-Ladbrokes_Logo.svg.png",
  "paddy-power": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Paddy_Power_Logo.svg/2560px-Paddy_Power_Logo.svg.png",
  "sky-bet": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Sky_Bet_logo.svg/2560px-Sky_Bet_logo.svg.png",
  "betfair": "https://upload.wikimedia.org/wikipedia/en/thumb/b/b0/Betfair_logo.svg/1200px-Betfair_logo.svg.png",
  "sporting-bet": "https://www.yogonet.com/storage/news/images/cover/2020072117172978779.jpg",
  "williamhill": "https://www.caesars.com/content/dam/william-hill/logos/wh-logo.svg",
  "caesars": "https://www.covers.com/sites/covers.com/files/Caesars-Sportsbook-Covers.png",
  "fox-bet": "https://www.compare.bet/img/uploads/bookmakers/logos_normal/fox-bet-logo.png",
  "betrivers": "https://www.yogonet.com/storage/news/images/cover/2021030317471848791.jpg",
  "borgata": "https://www.casino.org/news/wp-content/uploads/2022/02/Borgata-Sports-Logo.png",
  "circasports": "https://www.vegas.com/wp-content/uploads/2021/09/circa-sports-logo.png",
  "superbook": "https://superbook.com/wp-content/uploads/2023/01/superbook-sports-logo.svg",
  "wynnbet": "https://cms. WynnBET .com/wp-content/uploads/2021/07/WynnBET _logos_Horizontal_DarkBG.svg",
  "thescore": "https://www.thescore.bet/cms/dist/img/logos/theScoreBet_logo_horizontal.svg",
  "betfred": "https://www.casino.org/news/wp-content/uploads/2022/02/Betfred-Sports-Logo.png",
  "golden-nugget": "https://www.yogonet.com/storage/news/images/cover/2021072817502491491.png",
  "tipico": "https://logos-world.net/wp-content/uploads/2023/08/Tipico-Logo.png",
  "playup": "https://playup.com/wp-content/uploads/2022/03/PlayUp_Logo.svg",
  "betonline": "https://www.sportsbettingny.com/wp-content/uploads/2023/03/betonline-logo.png",
  " Bovada": "https://www.sportsbettingny.com/wp-content/uploads/2023/03/bovada-logo.png",
  "gtbets": "https://www.safestbettingsites.com/wp-content/uploads/2019/08/gtbets-logo.png",
  "intertops": "https://www.safestbettingsites.com/wp-content/uploads/2019/08/intertops-logo.png",
  "jazzsports": "https://www.safestbettingsites.com/wp-content/uploads/2020/07/jazzsports-logo.png",
  "sportsinteraction": "https://www.online-casinos.ca/wp-content/uploads/2019/07/sports-interaction-logo.png",
  "powerplay": "https://www.online-casinos.ca/wp-content/uploads/2020/06/powerplay-sportsbook-logo.png",
  "northstarbets": "https://www.online-casinos.ca/wp-content/uploads/2022/05/northstar-bets-logo.png",
  "coolbet": "https://www.online-casinos.ca/wp-content/uploads/2020/06/coolbet-logo.png",
  "unibet-ca": "https://www.online-casinos.ca/wp-content/uploads/2019/07/unibet-logo.png",
  "bet99": "https://www.online-casinos.ca/wp-content/uploads/2020/06/bet99-logo.png",
  "comeon": "https://www.online-casinos.ca/wp-content/uploads/2020/06/comeon-logo.png",
  "leovegas": "https://www.online-casinos.ca/wp-content/uploads/2019/07/leovegas-logo.png",
  "betano": "https://logovector.net/wp-content/uploads/2023/10/betano-logo-logovector.net_.png",
};

export const SPORTSBOOK_NAMES: Dictionary<string> = {
  draftkings: "DraftKings",
  betmgm: "BetMGM",
  fanduel: "FanDuel",
  "william-hill": "William Hill",
  "points-bet": "PointsBet",
  unibet: "Unibet",
  "888sport": "888sport",
  betway: "Betway",
  bwin: "Bwin",
  coral: "Coral",
  ladbrokes: "Ladbrokes",
  "paddy-power": "Paddy Power",
  "sky-bet": "Sky Bet",
  betfair: "Betfair",
  "sporting-bet": "Sporting Bet",
  williamhill: "William Hill",
  caesars: "Caesars",
  "fox-bet": "Fox Bet",
  betrivers: "BetRivers",
  borgata: "Borgata",
  circasports: "Circa Sports",
  superbook: "Superbook",
  wynnbet: "WynnBet",
  thescore: "theScore",
  betfred: "Betfred",
  "golden-nugget": "Golden Nugget",
  tipico: "Tipico",
  playup: "PlayUp",
  betonline: "BetOnline",
  Bovada: "Bovada",
  gtbets: "GTbets",
  intertops: "Intertops",
  jazzsports: "JazzSports",
  sportsinteraction: "Sports Interaction",
  powerplay: "PowerPlay",
  northstarbets: "NorthStarBets",
  coolbet: "Coolbet",
  "unibet-ca": "Unibet CA",
  bet99: "Bet99",
  comeon: "ComeOn",
  leovegas: "LeoVegas",
  betano: "Betano",
};
