// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blhbyhoycbvpjgcxpzxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsaGJ5aG95Y2J2cGpnY3hwenh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMTM5NzAsImV4cCI6MjA2MDc4OTk3MH0.UDlTOH81ypITt-L3UgPzAmz2Jdf4zxNyeFY_mfY1Q_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);